stages:
  - build
  - tests
  - bandit
  - dependency-check
  - stage
  - deploy

build:
  image: docker:latest
  stage: build
  script:
    - docker build -t flask/hdb -f ./config/Dockerfile .

test_job:
  image: python:3.10-slim
  stage: tests
  script:
    - export "DATABASE_URI=$DATABASE_URI"
    - export "SECRET_KEY=$SECRET_KEY"
    - pip install --no-cache-dir pipenv
    - pipenv install 
    - pipenv install pytest
    - pipenv run pytest todo_project/todo_project/tests/test_routes.py
  
bandit_job:
  image: python:3.10-slim
  stage: bandit
  script:
    - pip install --no-cache-dir pipenv
    - pipenv install bandit
    - pipenv run bandit -r todo_project/todo_project --exclude venv,tests --severity-level medium --confidence-level medium 

dependency-check:
  image: docker:latest
  stage: dependency-check
  script:
    - docker run --rm --volume $(pwd):/src owasp/dependency-check --project "todo_project" --scan /src

stage:
  image: docker:latest
  stage: stage
  script:
    - docker stop flask-stage && docker rm flask-stage
    - docker run -d --name flask-stage --network gitlab --restart always -e "SECRET_KEY=$SECRET_KEY" -e "DATABASE_URI=$DATABASE_URI" -v /dev/log:/dev/log -p 8000:9000 flask/hdb

deploy:
  image: docker:latest
  stage: deploy
  script:
    - docker stop flask && docker rm flask
    - docker run -d --name flask --network gitlab --restart always -e "SECRET_KEY=$SECRET_KEY" -e "DATABASE_URI=$DATABASE_URI" -v /dev/log:/dev/log -p 9000:9000 flask/hdb